# -*- coding: utf-8 -*-
"""lists, Tuples, dictionary, sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ErAbc5VEGbaCEHmdxWTHJhS43PoRm14O

# lists
"""

# lists are the collection of ordeed and mutable data.
# a=[]. separated by coma(,).multiple data types

furits=["apple","banana",123,1.12]
print(furits)

"""**lists slicing**"""

a=["Ironman","Captain America","Thor","Hulk"]
print(a[1])

print(a[-3])

print(a[1:3])

print(a[:2])

print(a[2:])

print(a[::2])

print(a[::-1])

print(a[-1:-4:-1])

"""**list Iteration**"""

# iteration using for loop
a=["Ironman","Captain America","Thor","Hulk"]
for i in a:
    print(i)

# iteration using for loop with range and lenght function
for i in range (len(a)):
  print(a[i])

# iteration using while loop
a=["Ironman","Captain America","Thor","Hulk"]
i=0
while i<len(a):
    print(a[i])
    i+=1

# using short-hand for loop
a=["Ironman","Captain America","Thor","Hulk"]
[print(i) for i in a]

"""**lists funtions**"""

# to find the lenght of a list
a=["Ironman","Captain America","Thor","Hulk"]
print(len(a))

# to count an occurance of a particular element
a=["Ironman","Captain America","Thor","Hulk","Thor"]
print(a.count("Thor"))

# to add to the list
a=["Ironman","Captain America","Thor","Hulk"]
a.append("Spiderman") # add at the last of string
print(a)

# to add to a spectific location
a.insert(3,"Black Panther")
print(a)

# to remove from a list
a.remove("Black Panther")
print(a)
a.remove("Thor")
print(a)

# to remove from a certain location
print(a.pop(1))
print(a)

# to create a copy of a list
b=a.copy()
print(b)

# to access an element
print(a[2])
print(a.index("Hulk"))

# to entend the list
c=["Antman","Captain Marvel"]
a.extend(c)
print(a)

# to reverse the list
a.reverse()
print(a)

# to short the list
a.sort()
print(a)
a.sort(reverse=True)
print(a)

# to clear all the data from the list
a.clear()
print(a)

"""**list comprehension**"""

li=[40,23,40]
l2=[]
for i in li:
  if i >30 :
    l2.append(i)
print(l2)

l3=[i for i in li if i>30]
print(l3)

l4=[i for i in li]
print(l4)

"""# **problems**

**["Ross","Rachel","Monica","Joe"]**
"""

A=["Ross","Rachel","Monica","Joe"]
print(A)

"""**write a program to swap first and forth element.**"""

A[0],A[3]=A[3],A[0]
print(A)

"""**write a program to add a new value at second position.**"""

A.insert(1,"Chandler")
print(A)

"""**write a program to delete a value from 3 position.**"""

A.pop(2)
print(A)

"""**[13,7,12,10]**"""

B=[13,7,12,10]
print(B)

"""**write a program to multiply all the numbers in the list.**"""

mul=1
for i in B:
  mul*=i
print(mul)

"""**write a program to get the largest number from the list.**"""

B.sort()
print(B[-1])

"""**write a program to get hte smallest number from the list.**"""

B.sort()
print(B[0])

"""# Tuples"""

# ordered and un-mutable data
# ---> ()
# ---> un-mutable no add , update , remove
# ---> separated by coma(,)
# ---> multiple datatype in it

a=("apple","mango","banana")
print(type(a))

a="apple","mango","banana",16,1.34
print(type(a))

b="ironman"
print(type(b))

b="ironman",
print(type(b))

"""**slicing and iteration in typles**"""

a=("OnePlus","Vivo","Redmi","SumSung","Nokia")
print(a[1:3])

print(a[:3])

print(a[2:])

print(a[1::2])

print(a[::-1])

print(a[2::-1])

for i in a:
  print(i)

for i in range(len(a)):
  print(a[i])

i=0
while i<len(a):
  print(a[i])
  i+=1

"""**convertion of tuples and tuples funtions**"""

a=("OnePlus","Vivo","Redmi","SumSung","Nokia","Vivo")
print(a.index("Redmi"))
print("before convertion ",type(a))

a=list(a)
print("after convertion ",type(a))

a.append("Iphone")

print(a)

a=tuple(a)

print(type(a))

a.count("Vivo")

"""# Dictionary"""

# write data in the form of keys and values
# ---> enclosed inside curly brackets{}
# --->  key values separated by colon
# ---> every key pair separated by a coma(,)

employee={"name":"David","age":24,"gender":"male"}
print(employee)

print(employee["gender"])
print(employee.values())

# iteration in dictionary

for x in employee:
  print(x)

for i in employee:
  print(employee[i])

print(employee.keys())

for i,j in employee.items():
  print(i,j)

# dictionary functions
Student={"name":"Jon","class":"6th","roll_no":23}
print(Student)

# get
x=Student.get("name")
print(x)

# items
x=Student.items()
print(x)

# keys
x=Student.keys()
print(x)

# values
x=Student.values()
print(x)

# copy
d=Student.copy()
print(d)

# setdefault
x=Student.setdefault("name","David")
print(x)

# update
Student.update({"name":"David"})
print(Student)

# pop
Student.pop("name")
print(Student)

# popitems
Student.popitem()
print(Student)

# clear
Student.clear()
print(Student)

# NESTED DICTIONARY
# ---> dictionary inside a dictionary

employee={1:{"name":"Jon","age":23},
          2:{"name":"Lisa","age":24},
          3:{"name":"David","age":25}}
print(employee)

print(employee[1])

print(employee[2]["name"])

"""# **JSON**"""

import json
# java script object notation
json_data='{"name":"David","age":13,"markes":87}'
print(type(json_data))

# to load
x=json.loads(json_data)
print(type(x))

x["age"]

"""# **Problems**

**write a python program to sort a dictionary values**
"""

a={"a":1,"b":2,"c":3}
print(a)
a=sorted(a.values())
print(a)

"""**write a python script to print a dictionary where th keys are numbers between 1 to 15 and values are square of keys**"""

a={}
for i in range(1,16):
  a[i]=i**2
print(a)

"""**write a program to multiply all items in a dictionary**"""

a={"a":1,"b":2,"c":3}
mul=1
for i in a:
  mul*=a[i]
print(mul)

a={"a":1,"b":2,"c":3}
mul=1
for i in a.values():
  mul*=i
print(mul)

"""**write a python program to short a dictionary by key**"""

a={1:"a",2:"b",3:"c",4:"d"}
a=sorted(a.keys())
print(a)

"""**student_data={"name":"David","age":13,"markes":87}**"""

student_data={"name":"David","age":13,"markes":87}
print(student_data)

"""**convert the dic into JSON format**"""

import json
print(type(student_data))
student_data_json=json.dumps(student_data)
print(type(student_data_json))
print(student_data_json)

"""**Acess the value of age from the given data**"""

data =json.loads(student_data_json)
print(data["age"])

"""**pretty print JSON data**"""

data=json.dumps(student_data,indent=4,separators=(".","="))
print(data)

"""**sort the following Json keys and write them into a file**"""

with open ("sample.json","w") as f:
  json.dump(student_data,f,indent=4,sort_keys=True)

"""**Access the nested key marks from the following nested data**"""

student_data2="""{"student":{
  "grade":{
    "name":"David",
    "marks":{
      "physics":70}

    }}}"""

data =json.loads(student_data2)

print(data["student"]["grade"]["marks"])

"""# sets"""

# unordered collection of data
# --> no indexing
# --> unique
# --> mutable
# --> inside a curly brakets {}
# --> separated by coma ,

a={"Ironman","Hulk","Caption America","Thor"}
print(a)

for x in a:
  print(x)

# set functions

# add
a.add("Spiderman")
print(a)

# pop
a.pop()
print(a)

# remove
a.remove("Hulk")
print(a)

# discard
a.discard("Ironman")
print(a)

# copy
b=a.copy()
print(b)

# isdisjoint
a={"Ironman","Hulk","Caption America","Thor"}
b={"Spiderman","Antman"}
c={"Hulk","Thor"}
print(a.isdisjoint(c))
print(a.isdisjoint(b))

# issubset
print(a.issubset(b))
print(c.issubset(a))

# issuperset
print(a.issuperset(c))
print(c.issuperset(a))
#

# update
a.update(b)
print(a)

# clear
a.clear()
print(a)

a={"Ironman","Hulk","Caption America","Thor"}
b={"Spiderman","Antman","Caption America"}
c={"Hulk","Thor","Antman"}

# union
print(a.union(b))

# difference
print(a.difference(c))
print(a)

# diference update
a.difference_update(c)
print(a)

# intersection
# common elements
print(a.intersection(b))
print(a)

# intersection update
a.intersection_update(b)
print(a)

# symmetric difference
a={"Ironman","Hulk","Caption America","Thor"}
b={"Spiderman","Antman","Caption America"}
c={"Hulk","Thor","Antman"}
print(a.symmetric_difference(b))
# only give a and b un common values
print(a)

# symmetric dfference update
a.symmetric_difference_update(b)
print(a)

"""# problems

**write a program to fing max and min in a set**
"""

s={1,2,3,4,5,6,7,8,9}
print(max(s))
print(min(s))

"""**write a program to find common element in three list using sets**"""

a={1,2,3,4,5}
b={3,4,5,6,7}
c={5,6,7,8,9}
print(set(a)&set(b)&set(c))
print(a.intersection(b,c))

"""**write a program to find difference between two sets**"""

a={1,2,3,4,5}
b={3,4,5,6,7}
print(a.difference(b))
print(b.difference(a))

"""**write a python program to remove items from a set if it present in a set**"""

a={1,2,3,4,5,6}
a.discard(3)
print(a)

"""**write a program to check if a set is a subset of another set**"""

a={1,2,3,4,5,6}
b={2,3,4}
print(b.issubset(a))